version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs: 
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install syntax-error --no-package-lock --no-save --also=dev
      - run:
          name: Run test using nodejs << parameters.node-version >>
          command: node test.js
  push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: 
          name: Clone repo
          command: git clone --mirror https://github.com/BochilGaming/games-wabot.git
      - run:
          name: Change directory & Remote mirror repo & Update repo &
          command: cd games-wabot.git && pwd &&
                  git remote set-url --push origin https://github.com/BochilGaming/games-wabot-md.git && 
                  git fetch -p origin &&
                  git push --mirror
workflows:
  all-test:
    jobs:
      - test: 
          matrix:
            parameters:
              node-version: ['14.19', '16.14', '17.5']
  push-to-mirror:
    jobs:
      - push
