- name: Setup Node.js environment
  uses: actions/setup-node@v2.1.5
  
  steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '12'
- run: npm install
- run: npm start
